DROP TABLE IF EXISTS lineitem CASCADE;

CREATE TABLE lineitem (
    L_ORDERKEY    INT8 NOT NULL,
    L_PARTKEY     INTEGER NOT NULL,
    L_SUPPKEY     INTEGER NOT NULL,
    L_LINENUMBER  INTEGER NOT NULL,
    L_QUANTITY    FLOAT8 NOT NULL,
    L_EXTENDEDPRICE FLOAT8 NOT NULL,
    L_DISCOUNT    FLOAT8 NOT NULL,
    L_TAX         FLOAT8 NOT NULL,
    L_RETURNFLAG  CHAR(1) NOT NULL,
    L_LINESTATUS  CHAR(1) NOT NULL,
    L_SHIPDATE    DATE NOT NULL,
    L_COMMITDATE  DATE NOT NULL,
    L_RECEIPTDATE DATE NOT NULL,
    L_SHIPINSTRUCT CHAR(25) NOT NULL,
    L_SHIPMODE     CHAR(10) NOT NULL,
    L_COMMENT      VARCHAR(44) NOT NULL )
WITH (APPENDONLY=true, ORIENTATION=parquet);
